### PR TITLE
Add upper bound on numpy

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Build for PyPy is failing on aarch64 and win64. :man_shrugging:

**Comment by maresb** [comment]
@ricardov94, this is one reason I'd like for there to be upper bounds. Also, I can do this retroactively by submitting a repodata patch, but that's a lot of work.

**Comment by twiecki** [comment]
Do we even need pypy builds?

**Comment by maresb** [comment]
Only if people are using them. If nobody complains then no.

I think we should support on principle these sorts of projects which push innovation, as long as it's not too much effort. But "too much effort" is chasing down obscure build errors on platforms I don't have access to.

**Pull request merged**
