### PR TITLE
Add aarch64

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Review by twiecki — APPROVED** [review]

**Comment by maresb** [comment]
I'm waiting for someone to confirm that the package is not found when the above commands are executed on their system. That way I know for sure that Docker is using the right platform and not emulating `amd64`.

**Comment by twiecki** [comment]
```
(base) mambauser@36cab66b23f2:/tmp$ micromamba install -y -c conda-forge pytensor
conda-forge/linux-aarch64                            8.3MB @   1.8MB/s  7.7s
conda-forge/noarch                                  11.8MB @   1.5MB/s  7.9s
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ pytensor does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

**Comment by maresb** [comment]
Thanks @twiecki!

Looks like it's now available:

```
$ conda search -c conda-forge --platform linux-aarch64 "pytensor"
Loading channels: done
# Name                       Version           Build  Channel             
pytensor                      2.13.1 py310h0d1d2ea_1  conda-forge         
pytensor                      2.13.1 py311h1bf5055_1  conda-forge         
pytensor                      2.13.1  py38hed0da46_1  conda-forge         
pytensor                      2.13.1  py39hb874dab_1  conda-forge         
pytensor                      2.13.1  py39he8647fe_1  conda-forge   
```

Could you please try again?

**Comment by twiecki** [comment]
Can install and import!

**Comment by maresb** [comment]
That's excellent!!! Thanks for the assist!

**Pull request merged**
