### PR TITLE
Use accelerate for osx-arm64

### LINKED ISSUE #52: Rework BLAS config
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Figure out exactly what [this](https://discourse.pymc.io/t/performance-tip-if-youre-on-arm64-apples-m1-m2-chips-install-accelerate/12495/7) from @jonsedar is doing, and wrap it into this recipe.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### PR DESCRIPTION
**Pull request by maresb**
Closes #52 and #55

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Review by twiecki — APPROVED** [review]

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Ok, I think this is ready for testing.

[All artifacts](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=804950&view=artifacts&pathAsName=false&type=publishedArtifacts)

We should test these two artifacts in particular:
* [osx-arm64 py3.8 numpy1.22](https://artprodeus21.artifacts.visualstudio.com/A910fa339-c7c2-46e8-a579-7ea247548706/84710dde-1620-425b-80d0-4cf5baca359d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NvbmRhLWZvcmdlL3Byb2plY3RJZC84NDcxMGRkZS0xNjIwLTQyNWItODBkMC00Y2Y1YmFjYTM1OWQvYnVpbGRJZC84MDQ5NTAvYXJ0aWZhY3ROYW1lL2NvbmRhX2FydGlmYWN0c18yMDIzMTAxNi4zLjFfb3N4X2FybTY0X251bXB5MS4yMnB5dGhvbjMuOC5fX19fY3B5dGhvbg2/content?format=zip)
* [osx-arm64 py3.11 numpy1.23](https://artprodeus21.artifacts.visualstudio.com/A910fa339-c7c2-46e8-a579-7ea247548706/84710dde-1620-425b-80d0-4cf5baca359d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NvbmRhLWZvcmdlL3Byb2plY3RJZC84NDcxMGRkZS0xNjIwLTQyNWItODBkMC00Y2Y1YmFjYTM1OWQvYnVpbGRJZC84MDQ5NTAvYXJ0aWZhY3ROYW1lL2NvbmRhX2FydGlmYWN0c18yMDIzMTAxNi4zLjFfb3N4X2FybTY0X251bXB5MS4yM3B5dGhvbjMuMTEuX19fX2NweXRob241/content?format=zip)

Testing instructions:

Download the artifact and extract it. Then run a command to the effect of

```
micromamba create -n pytensor-osxarm-test -c conda-forge osx-arm64/pytensor-2.12.3-py311hbee6d41_3.conda
```

making sure that you *don't* install the `pytensor-base` file, since that's the minimal version without BLAS or compilers. Then run `python -c "import pytensor.configdefaults; import pytensor.tensor"` to check for import errors.

In case you see the error

```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ pytensor 2.12.3 py311hbee6d41_3 is uninstallable because it conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```

then try

```
micromamba config remove-key channel_priority
micromamba create ...
micromamba config set channel_priority strict
```

**Comment by twiecki** [comment]
```
>>micromamba create -n pytensor-osxarm-test -c conda-forge osx-arm64/pytensor-2.17.2-py311h20a70b2_1.conda

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

file:///Users/twiecki/Downloads/osx-arm64            1.7kB @   3.0MB/s  0.0s
file:///Users/twiecki/Downloads/noarch             127.0 B @ 841.1kB/s  0.0s
conda-forge/osx-arm64                                8.2MB @   7.6MB/s  1.3s
conda-forge/noarch                                  14.2MB @   8.0MB/s  2.1s
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ pytensor 2.17.2 py311h20a70b2_1 is uninstallable because it conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```

**Comment by twiecki** [comment]
```
>>micromamba activate pytensor-osxarm-test
(pytensor-osxarm-test) --(10:55:32)--(MacBook-Air-4)--(~/Downloads     )--()
>>python -c "import pytensor.configdefaults; import pytensor.tensor"
(pytensor-osxarm-test) --(10:56:03)--(MacBook-Air-4)--(~/Downloads     )--()
>>python -c "import pytensor; print(pytensor.config.blas__ldflags)"
-L/Users/twiecki/micromamba/envs/pytensor-osxarm-test/lib -lcblas -lblas -lcblas -lblas -Wl,-rpath,/Users/twiecki/micromamba/envs/pytensor-osxarm-test/lib
```

Seems to have worked!

**Comment by twiecki** [comment]
In the `[osx-arm64 py3.8 numpy1.22](https://artprodeus21.artifacts.visualstudio.com/A910fa339-c7c2-46e8-a579-7ea247548706/84710dde-1620-425b-80d0-4cf5baca359d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NvbmRhLWZvcmdlL3Byb2plY3RJZC84NDcxMGRkZS0xNjIwLTQyNWItODBkMC00Y2Y1YmFjYTM1OWQvYnVpbGRJZC84MDQ5NTAvYXJ0aWZhY3ROYW1lL2NvbmRhX2FydGlmYWN0c18yMDIzMTAxNi4zLjFfb3N4X2FybTY0X251bXB5MS4yMnB5dGhvbjMuOC5fX19fY3B5dGhvbg2/content?format=zip)` package, the osx-arm64 directory is empty.

**Comment by maresb** [comment]
Ah! We skip `py<3.9`, so of course the 3.8 artifact is empty.

Could you please test the py3.9 package instead of the py3.8 package?

Ah, and in addition to making sure the import succeeds, would it be possible to do a quick and dirty benchmark to verify that new=fast and old=slow?

Finally, excellent timing with PyTensor v2.17.3, so let's cherry-pick this into there.

**Comment by twiecki** [comment]
> @twiecki, could you please test the py3.9 package instead of the py3.8 package?

Tested and confirm it works.

> Ah, and in addition to making sure the import succeeds, would it be possible to do a quick and dirty benchmark to verify that new=fast and old=slow?

I can confirm that accelerate gets installed and used and wasn't before.

> Finally, excellent timing with PyTensor v2.17.3, so let's cherry-pick this into there.

Great!

**Comment by maresb** [comment]
Superseded by #72

**Pull request closed without merging**
